version: '3'

services:
  users_groups_postgres:
    image: arm32v7/postgres:latest
    container_name: users_groups_postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=pibardos
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PIBARDOS_APP}
      - POSTGRES_DB=pibardos_app
    volumes:
      - ../go/user_service/db:/docker-entrypoint-initdb.d/
      - /data/postgres_data_pibardos_app:/var/lib/postgresql/data

  calendar_postgres:
    image: arm32v7/postgres:latest
    container_name: calendar_postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=pibardos
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PIBARDOS_APP}
      - POSTGRES_DB=pibardos_app
    volumes:
      - ../go/calendar_service/db:/docker-entrypoint-initdb.d/
      - /data/postgres_data_pibardos_app:/var/lib/postgresql/data

networks: 
  default: 
    external: 
      name: pibardos_app_network