version: '3'

services:
  go-test-api:
    build: ../go/test_service
    container_name: go-test-api
    restart: always
    expose:
    - "5000"
    environment:
      - VIRTUAL_PORT=5000
      - VIRTUAL_PATH=/test_api/
      - VIRTUAL_DEST=/
      - VIRTUAL_HOST=api.pibardosapp.com
      - LETSENCRYPT_HOST=api.pibardosapp.com
      - LETSENCRYPT_EMAIL=lanusseagustin@gmail.com

networks: 
  default: 
    external: 
      name: pibardos_app_network
