version: '3'

services:
  ########################
  #### group_service #####
  ########################
  group_service:
    build: ../go/group_service
    container_name: group_service
    restart: always
    ports:
      - 5000:5000
    expose:
      - "5000"
    environment:
      - API_PORT=5000
      - POSTGRES_DB=pibardos_app
      - POSTGRES_CONTAINER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PWD=${POSTGRES_PASSWORD_PIBARDOS_APP}
      - VIRTUAL_PORT=5000
      - VIRTUAL_PATH=/groups/
      - VIRTUAL_DEST=/
      - VIRTUAL_HOST=api.pibardosapp.com
      - LETSENCRYPT_HOST=api.pibardosapp.com
      - LETSENCRYPT_EMAIL=lanusseagustin@gmail.com

networks: 
  default: 
    external: 
      name: pibardos_app_network
