version: '3'

services:
  ########################
  ##### nging-proxy ######
  ########################
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  ########################
  ##### letsencrypt ######
  ########################
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    restart: always
    container_name: letsencrypt
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy

  ########################
  ####### ddclient #######
  ########################
  ddclient:
    image: lscr.io/linuxserver/ddclient:arm32v7-latest
    restart: unless-stopped
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montevideo
    volumes:
      - ../volumes/ddclient:/config

  ########################
  ###### nginx-home ######
  ########################
  nginx-static-page:
    image: nginx
    restart: always
    container_name: nginx-static-page
    expose:
      - "80"
    volumes:
      - ../volumes/www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=pibardosapp.com,www.pibardosapp.com
      - LETSENCRYPT_HOST=pibardosapp.com,www.pibardosapp.com
      - LETSENCRYPT_EMAIL=lanusseagustin@gmail.com

  ########################
  ####### portainer ######
  ########################
  portainer:
    image: portainer/portainer-ce:linux-arm
    restart: unless-stopped
    container_name: portainer
    expose:
      - "9000"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    environment:
      - VIRTUAL_HOST=portainer.pibardosapp.com
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.pibardosapp.com
      - LETSENCRYPT_EMAIL=lanusseagustin@gmail.com

  ########################
  ####### postgres #######
  ########################
  postgres:
    image: arm32v7/postgres:latest
    container_name: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=pibardos
      - POSTGRES_PASSWORD=${POSTGRES_PIBARDOS_APP_PWD}
      - POSTGRES_DB=pibardos_app
    volumes:
      - ../db:/docker-entrypoint-initdb.d/
      - /data/postgres_data_pibardos_app:/var/lib/postgresql/data

  ########################
  ######## adminer #######
  ########################
  adminer:
    image: arm32v7/adminer:latest
    container_name: adminer
    restart: always
    expose:
      - "8080"
    environment:
      - ADMINER_DESIGN=galkaev
      - VIRTUAL_HOST=adminer.pibardosapp.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=adminer.pibardosapp.com
      - LETSENCRYPT_EMAIL=lanusseagustin@gmail.com
      
volumes:
  certs:
  html:
  vhostd:
  confd:
  portainer:

networks: 
  default: 
    external: 
      name: pibardos_app_network
