version: '3'

services:
 node-service:
    build: ../node
    container_name: node-service
    restart: always
    expose:
      - "3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/node_api/
      - VIRTUAL_DEST=/
      - VIRTUAL_HOST=api.pibardosapp.com
      - LETSENCRYPT_HOST=api.pibardosapp.com
      - LETSENCRYPT_EMAIL=lanusseagustin@gmail.com

networks: 
  default: 
    external: 
      name: pibardos_app_network
