version: '3'

services:
##########################
# Authentication service #
##########################
  authentication-service:
    container_name: authentication-service
    build:
      context: ../nodejs
      dockerfile: Dockerfile.prod
      args:
        - BUILD_CONTEXT=authentication-service
    restart: always
    expose:
      - "3000"
    environment:
      - PORT=3000
      - MONGODB_URI_CONNECTION=${AUTHENTICATION_SERVICE_MONGO_URI}
      - BCRYPT_SALT_ROUNDS=12
      - ACCESS_TOKEN_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_EXP_TIME=7d
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/auth/
      - VIRTUAL_DEST=/
      - VIRTUAL_HOST=api.pibardosapp.com
      - LETSENCRYPT_HOST=api.pibardosapp.com
      - LETSENCRYPT_EMAIL=lanusseagustin@gmail.com

networks: 
  default: 
    external: 
      name: pibardos_app_network
