version: '3'

services:
  auth-service:
    container_name: auth-service
    build:
      context: ../../
      dockerfile: Dockerfile.dev
      args:
        - BUILD_CONTEXT=authentication-service
    restart: always
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGODB_URI_CONNECTION=mongodb://mongodb:27017/auth-service
      - BCRYPT_SALT_ROUNDS=12
      - ACCESS_TOKEN_SECRET=jwtsecret
      - ACCESS_TOKEN_EXP_TIME=10m
      - RABBITMQ_URI_CONNECTION=amqp://rabbitmquser:rabbitmqpassword@rabbitmq
    links:
      - mongodb
      - rabbitmq

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    expose:
      - 27017

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - 5672
    environment:
      - AMQP_URL='amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword