version: '3'

services:
  auth-service:
    container_name: auth-service
    build:
      context: ../../
      dockerfile: Dockerfile.dev
      args:
        - BUILD_CONTEXT=authentication-service
    restart: always
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGODB_URI_CONNECTION=mongodb://mongodb:27017/auth-service
      - BCRYPT_SALT_ROUNDS=12
      - ACCESS_TOKEN_SECRET=jwtsecret
      - ACCESS_TOKEN_EXP_TIME=10m
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    expose:
      - 27017