version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    restart: always
    container_name: letsencrypt
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy

  portainer:
    image: portainer/portainer-ce:linux-arm
    restart: unless-stopped
    container_name: portainer
    expose:
      - "9000"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    environment:
      - VIRTUAL_HOST=portainer.pibardosapp.com
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.pibardosapp.com
      - LETSENCRYPT_EMAIL=lanusseagustin@gmail.com

  ddclient:
    image: lscr.io/linuxserver/ddclient:arm32v7-latest
    restart: unless-stopped
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montevideo
    volumes:
      - ./volumes/ddclient:/config

  nginx-static-page:
    image: nginx
    restart: always
    container_name: nginx-static-page
    expose:
      - "80"
    volumes:
      - ./volumes/www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=pibardosapp.com,www.pibardosapp.com
      - LETSENCRYPT_HOST=pibardosapp.com,www.pibardosapp.com
      - LETSENCRYPT_EMAIL=lanusseagustin@gmail.com

  node-service:
    build: ./node
    container_name: node-service
    expose:
      - "3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/node_api
      - VIRTUAL_DEST=/
      - VIRTUAL_HOST=api.pibardosapp.com
      - LETSENCRYPT_HOST=api.pibardosapp.com
      - LETSENCRYPT_EMAIL=lanusseagustin@gmail.com

  go-test-api:
    build: ./go/test_service
    container_name: go-test-api
    expose:
    - "5000"
    environment:
      - VIRTUAL_PORT=5000
      - VIRTUAL_PATH=/test_api
      - VIRTUAL_HOST=api.pibardosapp.com
      - LETSENCRYPT_HOST=api.pibardosapp.com
      - LETSENCRYPT_EMAIL=lanusseagustin@gmail.com

volumes:
  certs:
  html:
  vhostd:
  confd:
  portainer:
